# Generated by Django 5.0.6 on 2024-05-13 14:27

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_sku_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['top', 'left'], default='image1.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[200, 200], upload_to='product_images'),
        ),
    ]
