# Generated by Django 5.0.6 on 2024-05-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cart_added_alter_priceupdate_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
