# Generated by Django 5.0.6 on 2024-05-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_promo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='newPrice',
            new_name='discount',
        ),
    ]
